# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0be9ff7fc78f6217274a3b5fa23a92d8dd04674f2b60c5fe8654d20a7593bcbd4c2e6abb3c9e7866a8f8721905cd6de1d1f71f4aebf2ff9f6e9d59c182248d6e

test:
  secret_key_base: e22a42b38c3338b5d12407ca0bb34a7834bef2953ca5fc7de5fc0f7fd30ad3515f43da1e3e00571357972f2ddf28b31a0d7a60bf638f9c676f1ff0ec419f7bb4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
